### ISSUE TITLE
Zod validation failing specifically for "cognitivecomputations/dolphin-mixtral-8x22b"

### ISSUE THREAD

**Issue by ichabodcole** [OpenRouterTeam/ai-sdk-provider#3]
Hi, I'm currently using the vercel sdk using the `steamText` function, and currently hitting an issue with the response from a specific model `cognitivecomputations/dolphin-mixtral-8x22b`, other models I have tested seem to work as expected. I'm not sure if the issue is with this library or the Vercel library, but I figured I'd let check in here first.

Below is the validation error I'm receiving.

```
"Type validation failed: Value: {"id":"gen-9KTZBnGp8T1l51fYzRMuvaAHwbtt","provider":"Novita","model":"cognitivecomputations/dolphin-mixtral-8x22b","object":"chat.completion.chunk","created":1727133797,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null,"logprobs":{"tokens":null,"token_logprobs":null,"top_logprobs":null,"text_offset":null}}]}.
Error message: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "array",
            "received": "undefined",
            "path": [
              "choices",
              0,
              "logprobs",
              "content"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "error"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]"
```

Here is the streaming response data which causes the Zod validation error, it appears to be due to the "logprobs" value.
```
{
  "id": "gen-9KTZBnGp8T1l51fYzRMuvaAHwbtt",
  "provider": "Novita",
  "model": "cognitivecomputations/dolphin-mixtral-8x22b",
  "object": "chat.completion.chunk",
  "created": 1727133797,
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": "he "
      },
      "finish_reason": null,
      "logprobs": {
        "tokens": null,
        "token_logprobs": null,
        "top_logprobs": null,
        "text_offset": null
      }
    }
  ]
}
```

However the below succeeds with no issues, with `logprobs` set to null.
```
{
  "id": "gen-YMizbTfPRjAeRt85myCTbAadX5tg",
  "provider": "Lepton",
  "model": "cognitivecomputations/dolphin-mixtral-8x7b",
  "object": "chat.completion.chunk",
  "created": 1727134025,
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": "iolets are"
      },
      "finish_reason": null,
      "logprobs": null
    }
  ]
}
```

**Comment by ichabodcole** [comment]
Issue appears to be with `map-openrouter-chat-logprobs.ts`.

```
export function mapOpenRouterChatLogProbsOutput(
  logprobs: OpenRouterChatLogProbs | null | undefined
): LanguageModelV1LogProbs | null | undefined {
  return (
    logprobs?.content?.map(({ token, logprob, top_logprobs }) => ({
      token,
      logprob,
      topLogprobs: top_logprobs
        ? top_logprobs.map(({ token, logprob }) => ({
            token,
            logprob,
          }))
        : [],
    }))
  );
}
```

**Comment by deankerr** [comment]
Either Novita or OpenRouter are using a nonstandard value for `logprobs` in their stream chunks. 

It appears they're sending `logprobs: { tokens: null, token_logprobs: null, top_logprobs: null, text_offset: null}` when they should just be sending `logprobs: null`. This is triggering the strict zod validation. This also affects `@ai-sdk/openai`, but OpenAI's own node client appears to just ignore this value and stream text successfully.

The validator could be made less strict to handle this case, or OpenRouter could look into it on their end. It's a null value in spirit anyway, so it's annoying that `ai` fails on this instead of ignoring it.

**Comment by ichabodcole** [comment]
@daun-io Do you have an opinion on which code based this should be handled in?

**Comment by bobcoi03** [comment]
I got the same error and I just disabled NovitaAI in OpenRouter as a provider and all of my requests returned to normal

**Comment by louisgv** [comment]
Pushed a fix to address the weird logitbias shape coming from Novita - let me know if the problem persists!
