### ISSUE TITLE
What's the benefits of using this provider instead of `@ai-sdk/openai`?

### ISSUE THREAD

**Issue by wong2** [OpenRouterTeam/ai-sdk-provider#4]
It would be helpful to explain the difference between the two. I can use OpenRouter's model through `@ai-sdk/openai`, and it's actively maintained.

**Comment by daun-io** [comment]
hi, the last time we checked, we couldn't use openrouter's model ids with @ai-sdk/openai.
the current implementation has an extra feature like passing an extra body.
